-- ============================================================
-- CARGA DE MODELO Y DATOS — Caso NodoExpress (versión piloto, 20 tablas)
-- Proyecto Transversal (Evaluación Final Transversal) — BDY1103
-- Taller de Base de Datos — Trabajo grupal, entregas EA1+EA2+EA3
-- ============================================================
-- Ejecuta este script completo en el esquema de trabajo del grupo
-- antes de comenzar. Puedes volver a ejecutarlo para dejar los
-- datos como al inicio (primero elimina las tablas si ya existen,
-- en orden inverso al de creación por las FOREIGN KEY).
--


-- ------------------------------------------------------------
-- DDL (20 tablas)
-- ------------------------------------------------------------

CREATE TABLE ciudad (
  ciudad_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre    VARCHAR2(60) NOT NULL,
  CONSTRAINT pk_ciudad PRIMARY KEY (ciudad_id)
);

CREATE TABLE nivel_fidelizacion (
  nivel_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre         VARCHAR2(30) NOT NULL,
  puntos_minimos NUMBER NOT NULL,
  beneficio_pct  NUMBER(5,2) NOT NULL,
  CONSTRAINT pk_nivel_fidelizacion PRIMARY KEY (nivel_id)
);

CREATE TABLE cliente (
  cliente_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre          VARCHAR2(100) NOT NULL,
  email           VARCHAR2(120) NOT NULL,
  telefono        VARCHAR2(20),
  ciudad_id       NUMBER NOT NULL,
  nivel_id        NUMBER NOT NULL,
  fecha_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_cliente PRIMARY KEY (cliente_id),
  CONSTRAINT uq_cliente_email UNIQUE (email),
  CONSTRAINT fk_cliente_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad (ciudad_id),
  CONSTRAINT fk_cliente_nivel FOREIGN KEY (nivel_id) REFERENCES nivel_fidelizacion (nivel_id)
);

CREATE TABLE vendedor (
  vendedor_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre_comercial VARCHAR2(100) NOT NULL,
  email           VARCHAR2(120) NOT NULL,
  ciudad_id       NUMBER NOT NULL,
  fecha_registro  DATE DEFAULT SYSDATE NOT NULL,
  activo          CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_vendedor PRIMARY KEY (vendedor_id),
  CONSTRAINT uq_vendedor_email UNIQUE (email),
  CONSTRAINT fk_vendedor_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad (ciudad_id),
  CONSTRAINT ck_vendedor_activo CHECK (activo IN ('S','N'))
);

CREATE TABLE bodega (
  bodega_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre        VARCHAR2(100) NOT NULL,
  ciudad_id     NUMBER NOT NULL,
  capacidad_m3  NUMBER NOT NULL,
  CONSTRAINT pk_bodega PRIMARY KEY (bodega_id),
  CONSTRAINT fk_bodega_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad (ciudad_id)
);

CREATE TABLE transportista (
  transportista_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre           VARCHAR2(100) NOT NULL,
  tipo_vehiculo    VARCHAR2(20) NOT NULL,
  ciudad_base_id   NUMBER NOT NULL,
  disponible       CHAR(1) DEFAULT 'S' NOT NULL,
  rating_promedio  NUMBER(3,2) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_transportista PRIMARY KEY (transportista_id),
  CONSTRAINT fk_transportista_ciudad FOREIGN KEY (ciudad_base_id) REFERENCES ciudad (ciudad_id),
  CONSTRAINT ck_transportista_vehiculo CHECK (tipo_vehiculo IN ('MOTO','FURGON','CAMION')),
  CONSTRAINT ck_transportista_disponible CHECK (disponible IN ('S','N')),
  CONSTRAINT ck_transportista_rating CHECK (rating_promedio BETWEEN 0 AND 5)
);

-- categoria y marca se aplanaron como columnas de texto (antes eran
-- catálogos aparte, sin ninguna RN ni objeto obligatorio apoyado en ellos).
CREATE TABLE producto (
  producto_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  vendedor_id  NUMBER NOT NULL,
  categoria    VARCHAR2(60) NOT NULL,
  marca        VARCHAR2(60) NOT NULL,
  nombre       VARCHAR2(120) NOT NULL,
  descripcion  VARCHAR2(300),
  precio       NUMBER(10,2) NOT NULL,
  activo       CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_producto PRIMARY KEY (producto_id),
  CONSTRAINT fk_producto_vendedor FOREIGN KEY (vendedor_id) REFERENCES vendedor (vendedor_id),
  CONSTRAINT ck_producto_precio CHECK (precio > 0),
  CONSTRAINT ck_producto_activo CHECK (activo IN ('S','N'))
);

CREATE TABLE inventario (
  bodega_id        NUMBER NOT NULL,
  producto_id      NUMBER NOT NULL,
  stock_disponible NUMBER NOT NULL,
  stock_reservado  NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT pk_inventario PRIMARY KEY (bodega_id, producto_id),
  CONSTRAINT fk_inventario_bodega FOREIGN KEY (bodega_id) REFERENCES bodega (bodega_id),
  CONSTRAINT fk_inventario_producto FOREIGN KEY (producto_id) REFERENCES producto (producto_id),
  CONSTRAINT ck_inventario_disponible CHECK (stock_disponible >= 0),
  CONSTRAINT ck_inventario_reservado CHECK (stock_reservado >= 0)
);

CREATE TABLE movimiento_inventario (
  movimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  bodega_id     NUMBER NOT NULL,
  producto_id   NUMBER NOT NULL,
  tipo          VARCHAR2(10) NOT NULL,
  cantidad      NUMBER NOT NULL,
  fecha         DATE DEFAULT SYSDATE NOT NULL,
  motivo        VARCHAR2(200),
  CONSTRAINT pk_movimiento_inventario PRIMARY KEY (movimiento_id),
  CONSTRAINT fk_movinv_bodega FOREIGN KEY (bodega_id) REFERENCES bodega (bodega_id),
  CONSTRAINT fk_movinv_producto FOREIGN KEY (producto_id) REFERENCES producto (producto_id),
  CONSTRAINT ck_movinv_tipo CHECK (tipo IN ('INGRESO','SALIDA','AJUSTE'))
);

-- medio_pago se aplanó como columna de texto de PAGO (antes era un
-- catálogo aparte de 3 filas, sin ninguna RN ni objeto obligatorio propio).
CREATE TABLE cupon (
  cupon_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  codigo         VARCHAR2(30) NOT NULL,
  descuento_pct  NUMBER(5,2) NOT NULL,
  fecha_inicio   DATE NOT NULL,
  fecha_fin      DATE NOT NULL,
  usos_maximos   NUMBER NOT NULL,
  usos_actuales  NUMBER DEFAULT 0 NOT NULL,
  activo         CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_cupon PRIMARY KEY (cupon_id),
  CONSTRAINT uq_cupon_codigo UNIQUE (codigo),
  CONSTRAINT ck_cupon_activo CHECK (activo IN ('S','N'))
);

-- direccion_entrega se aplanó dentro de PEDIDO (ciudad_id_entrega +
-- direccion_calle + direccion_referencia): ya no es una tabla propia con
-- reutilización entre pedidos del mismo cliente, pero la RN6 (costo de
-- envío según ciudad) y el objeto fn_costo_envio se apoyan igual en ella.
CREATE TABLE pedido (
  pedido_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
  cliente_id          NUMBER NOT NULL,
  bodega_id_origen    NUMBER NOT NULL,
  ciudad_id_entrega   NUMBER NOT NULL,
  direccion_calle     VARCHAR2(150) NOT NULL,
  direccion_referencia VARCHAR2(150),
  fecha_pedido        DATE DEFAULT SYSDATE NOT NULL,
  estado              VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
  CONSTRAINT pk_pedido PRIMARY KEY (pedido_id),
  CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id),
  CONSTRAINT fk_pedido_bodega FOREIGN KEY (bodega_id_origen) REFERENCES bodega (bodega_id),
  CONSTRAINT fk_pedido_ciudad_entrega FOREIGN KEY (ciudad_id_entrega) REFERENCES ciudad (ciudad_id),
  CONSTRAINT ck_pedido_estado CHECK (estado IN ('PENDIENTE','CONFIRMADO','EN_PREPARACION','DESPACHADO','ENTREGADO','CANCELADO'))
);

CREATE TABLE detalle_pedido (
  pedido_id       NUMBER NOT NULL,
  producto_id     NUMBER NOT NULL,
  cantidad        NUMBER NOT NULL,
  precio_unitario NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_detalle_pedido PRIMARY KEY (pedido_id, producto_id),
  CONSTRAINT fk_detped_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT fk_detped_producto FOREIGN KEY (producto_id) REFERENCES producto (producto_id),
  CONSTRAINT ck_detped_cantidad CHECK (cantidad > 0)
);

CREATE TABLE pago (
  pago_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id     NUMBER NOT NULL,
  medio_pago    VARCHAR2(20) NOT NULL,
  monto         NUMBER(10,2) NOT NULL,
  estado        VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
  fecha_pago    DATE,
  CONSTRAINT pk_pago PRIMARY KEY (pago_id),
  CONSTRAINT uq_pago_pedido UNIQUE (pedido_id),
  CONSTRAINT fk_pago_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT ck_pago_medio CHECK (medio_pago IN ('WEBPAY','TRANSFERENCIA','EFECTIVO')),
  CONSTRAINT ck_pago_estado CHECK (estado IN ('PENDIENTE','APROBADO','RECHAZADO'))
);

CREATE TABLE pedido_cupon (
  pedido_id        NUMBER NOT NULL,
  cupon_id         NUMBER NOT NULL,
  monto_descontado NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_pedido_cupon PRIMARY KEY (pedido_id),
  CONSTRAINT fk_pedcup_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT fk_pedcup_cupon FOREIGN KEY (cupon_id) REFERENCES cupon (cupon_id)
);

CREATE TABLE ruta (
  ruta_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  transportista_id NUMBER NOT NULL,
  bodega_id        NUMBER NOT NULL,
  fecha            DATE NOT NULL,
  estado           VARCHAR2(15) DEFAULT 'PLANIFICADA' NOT NULL,
  CONSTRAINT pk_ruta PRIMARY KEY (ruta_id),
  CONSTRAINT fk_ruta_transportista FOREIGN KEY (transportista_id) REFERENCES transportista (transportista_id),
  CONSTRAINT fk_ruta_bodega FOREIGN KEY (bodega_id) REFERENCES bodega (bodega_id),
  CONSTRAINT ck_ruta_estado CHECK (estado IN ('PLANIFICADA','EN_CURSO','FINALIZADA'))
);

CREATE TABLE envio (
  envio_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id      NUMBER NOT NULL,
  ruta_id        NUMBER NOT NULL,
  fecha_despacho DATE NOT NULL,
  fecha_entrega  DATE,
  estado         VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
  distancia_km   NUMBER(6,2) NOT NULL,
  CONSTRAINT pk_envio PRIMARY KEY (envio_id),
  CONSTRAINT uq_envio_pedido UNIQUE (pedido_id),
  CONSTRAINT fk_envio_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT fk_envio_ruta FOREIGN KEY (ruta_id) REFERENCES ruta (ruta_id),
  CONSTRAINT ck_envio_estado CHECK (estado IN ('PENDIENTE','EN_RUTA','ENTREGADO','FALLIDO'))
);

CREATE TABLE tarifa_envio (
  tarifa_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ciudad_id    NUMBER NOT NULL,
  peso_max_kg  NUMBER(6,2) NOT NULL,
  costo        NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_tarifa_envio PRIMARY KEY (tarifa_id),
  CONSTRAINT fk_tarifa_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad (ciudad_id)
);

CREATE TABLE devolucion (
  devolucion_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id       NUMBER NOT NULL,
  motivo          VARCHAR2(200) NOT NULL,
  estado          VARCHAR2(15) DEFAULT 'SOLICITADA' NOT NULL,
  fecha_solicitud DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_devolucion PRIMARY KEY (devolucion_id),
  CONSTRAINT fk_devolucion_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT ck_devolucion_estado CHECK (estado IN ('SOLICITADA','APROBADA','RECHAZADA','COMPLETADA'))
);

CREATE TABLE detalle_devolucion (
  devolucion_id  NUMBER NOT NULL,
  producto_id    NUMBER NOT NULL,
  cantidad       NUMBER NOT NULL,
  motivo_detalle VARCHAR2(200),
  CONSTRAINT pk_detalle_devolucion PRIMARY KEY (devolucion_id, producto_id),
  CONSTRAINT fk_detdev_devolucion FOREIGN KEY (devolucion_id) REFERENCES devolucion (devolucion_id),
  CONSTRAINT fk_detdev_producto FOREIGN KEY (producto_id) REFERENCES producto (producto_id),
  CONSTRAINT ck_detdev_cantidad CHECK (cantidad > 0)
);

CREATE TABLE movimiento_puntos (
  movimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  cliente_id    NUMBER NOT NULL,
  pedido_id     NUMBER,
  tipo          VARCHAR2(10) NOT NULL,
  puntos        NUMBER(6) NOT NULL,
  fecha         DATE DEFAULT SYSDATE NOT NULL,
  descripcion   VARCHAR2(200),
  CONSTRAINT pk_movimiento_puntos PRIMARY KEY (movimiento_id),
  CONSTRAINT fk_movpts_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id),
  CONSTRAINT fk_movpts_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id),
  CONSTRAINT ck_movpts_tipo CHECK (tipo IN ('GANADO','CANJEADO')),
  CONSTRAINT ck_movpts_puntos CHECK (puntos > 0)
);

-- ------------------------------------------------------------
-- Datos de ejemplo
-- ------------------------------------------------------------

-- Catálogos geográficos y de fidelización
INSERT INTO ciudad (ciudad_id, nombre) VALUES (1, 'Santiago');
INSERT INTO ciudad (ciudad_id, nombre) VALUES (2, 'Puente Alto');
INSERT INTO ciudad (ciudad_id, nombre) VALUES (3, 'Vina del Mar');
INSERT INTO ciudad (ciudad_id, nombre) VALUES (4, 'Valparaiso');
INSERT INTO ciudad (ciudad_id, nombre) VALUES (5, 'Concepcion');

INSERT INTO nivel_fidelizacion (nivel_id, nombre, puntos_minimos, beneficio_pct) VALUES (1, 'BRONCE', 0, 0);
INSERT INTO nivel_fidelizacion (nivel_id, nombre, puntos_minimos, beneficio_pct) VALUES (2, 'PLATA', 50, 5);
INSERT INTO nivel_fidelizacion (nivel_id, nombre, puntos_minimos, beneficio_pct) VALUES (3, 'ORO', 150, 10);

-- Actores
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (1, 'Camila Rojas', 'camila.rojas@mail.cl', '+56911111111', 1, 1, DATE '2025-01-10');
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (2, 'Diego Fuentes', 'diego.fuentes@mail.cl', '+56922222222', 2, 1, DATE '2025-01-15');
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (3, 'Valentina Soto', 'valentina.soto@mail.cl', '+56933333333', 1, 1, DATE '2025-02-01');
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (4, 'Matias Herrera', 'matias.herrera@mail.cl', '+56944444444', 3, 1, DATE '2025-02-20');
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (5, 'Josefa Vera', 'josefa.vera@mail.cl', '+56955555555', 4, 1, DATE '2025-03-05');
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (6, 'Tomas Aguilar', 'tomas.aguilar@mail.cl', '+56966666666', 5, 1, DATE '2025-03-18');
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (7, 'Isidora Campos', 'isidora.campos@mail.cl', '+56977777777', 1, 1, DATE '2025-04-02');
INSERT INTO cliente (cliente_id, nombre, email, telefono, ciudad_id, nivel_id, fecha_registro) VALUES (8, 'Benjamin Nunez', 'benjamin.nunez@mail.cl', '+56988888888', 2, 1, DATE '2025-04-15');

INSERT INTO vendedor (vendedor_id, nombre_comercial, email, ciudad_id, fecha_registro, activo) VALUES (1, 'TecnoStgo', 'contacto@tecnostgo.cl', 1, DATE '2024-11-01', 'S');
INSERT INTO vendedor (vendedor_id, nombre_comercial, email, ciudad_id, fecha_registro, activo) VALUES (2, 'CasaHogar Express', 'contacto@casahogar.cl', 2, DATE '2024-11-05', 'S');
INSERT INTO vendedor (vendedor_id, nombre_comercial, email, ciudad_id, fecha_registro, activo) VALUES (3, 'DeportesSur', 'contacto@deportessur.cl', 5, DATE '2024-11-10', 'S');
INSERT INTO vendedor (vendedor_id, nombre_comercial, email, ciudad_id, fecha_registro, activo) VALUES (4, 'ElectroValpo', 'contacto@electrovalpo.cl', 4, DATE '2024-11-12', 'S');
INSERT INTO vendedor (vendedor_id, nombre_comercial, email, ciudad_id, fecha_registro, activo) VALUES (5, 'MueblesConce', 'contacto@mueblesconce.cl', 5, DATE '2024-11-15', 'S');
INSERT INTO vendedor (vendedor_id, nombre_comercial, email, ciudad_id, fecha_registro, activo) VALUES (6, 'CompuTodo', 'contacto@computodo.cl', 1, DATE '2024-11-20', 'S');

INSERT INTO bodega (bodega_id, nombre, ciudad_id, capacidad_m3) VALUES (1, 'Bodega Santiago Centro', 1, 5000);
INSERT INTO bodega (bodega_id, nombre, ciudad_id, capacidad_m3) VALUES (2, 'Bodega Puente Alto', 2, 3000);
INSERT INTO bodega (bodega_id, nombre, ciudad_id, capacidad_m3) VALUES (3, 'Bodega Valparaiso', 4, 4000);
INSERT INTO bodega (bodega_id, nombre, ciudad_id, capacidad_m3) VALUES (4, 'Bodega Concepcion', 5, 3500);

INSERT INTO transportista (transportista_id, nombre, tipo_vehiculo, ciudad_base_id, disponible, rating_promedio) VALUES (1, 'Ruben Diaz', 'MOTO', 1, 'S', 4.50);
INSERT INTO transportista (transportista_id, nombre, tipo_vehiculo, ciudad_base_id, disponible, rating_promedio) VALUES (2, 'Camila Reyes', 'FURGON', 1, 'S', 4.70);
INSERT INTO transportista (transportista_id, nombre, tipo_vehiculo, ciudad_base_id, disponible, rating_promedio) VALUES (3, 'Jorge Alarcon', 'MOTO', 2, 'N', 4.20);
INSERT INTO transportista (transportista_id, nombre, tipo_vehiculo, ciudad_base_id, disponible, rating_promedio) VALUES (4, 'Fernanda Leon', 'CAMION', 4, 'S', 4.60);
INSERT INTO transportista (transportista_id, nombre, tipo_vehiculo, ciudad_base_id, disponible, rating_promedio) VALUES (5, 'Matias Bravo', 'FURGON', 4, 'S', 4.10);
INSERT INTO transportista (transportista_id, nombre, tipo_vehiculo, ciudad_base_id, disponible, rating_promedio) VALUES (6, 'Sofia Vergara', 'MOTO', 5, 'S', 4.80);

-- Catálogo de productos (categoria/marca ahora en texto directo sobre PRODUCTO)
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (1, 1, 'Celulares', 'Samsung', 'Galaxy A15', 'Smartphone gama media', 189990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (2, 1, 'Celulares', 'Xiaomi', 'Redmi Note 13', 'Smartphone gama media Xiaomi', 149990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (3, 1, 'Computacion', 'HP', 'Notebook HP 15', 'Notebook 15 pulgadas', 459990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (4, 6, 'Computacion', 'HP', 'Monitor HP 24 pulgadas', 'Monitor Full HD', 129990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (5, 6, 'Computacion', 'Samsung', 'SSD 1TB Samsung', 'Disco de estado solido', 59990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (6, 2, 'Electrodomesticos', 'Oster', 'Batidora Oster', 'Batidora de pie', 39990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (7, 2, 'Electrodomesticos', 'LG', 'Refrigerador LG 300L', 'Refrigerador No Frost', 399990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (8, 2, 'Muebles', 'Ecomax', 'Silla de Comedor', 'Silla tapizada', 34990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (9, 5, 'Muebles', 'Ecomax', 'Mesa de Centro', 'Mesa de centro de madera', 79990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (10, 5, 'Muebles', 'Ecomax', 'Sofa 3 Cuerpos', 'Sofa tela antimanchas', 349990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (11, 3, 'Deporte', 'Nike', 'Zapatillas Running Nike', 'Zapatillas running unisex', 69990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (12, 3, 'Deporte', 'Nike', 'Polera Deportiva Nike', 'Polera dry-fit', 19990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (13, 4, 'Electrodomesticos', 'LG', 'Microondas LG', 'Microondas 20L', 89990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (14, 4, 'Celulares', 'Samsung', 'Tablet Galaxy Tab A9', 'Tablet 8.7 pulgadas', 179990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (15, 3, 'Deporte', 'Nike', 'Balon de Futbol Nike', 'Balon N5', 24990, 'S');
INSERT INTO producto (producto_id, vendedor_id, categoria, marca, nombre, descripcion, precio, activo) VALUES (16, 6, 'Computacion', 'Xiaomi', 'Mouse Inalambrico Xiaomi', 'Mouse optico inalambrico', 14990, 'S');

-- Inventario y movimientos (consistentes: stock_disponible = INGRESO - SALIDA/AJUSTE)
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (1, 1, 40, 2);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (1, 2, 35, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (1, 3, 15, 1);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (1, 4, 20, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (1, 5, 50, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (1, 16, 60, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (2, 6, 25, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (2, 7, 10, 1);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (2, 8, 18, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (2, 16, 15, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (3, 13, 14, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (3, 14, 22, 1);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (3, 1, 10, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (4, 9, 12, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (4, 10, 6, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (4, 11, 30, 2);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (4, 12, 45, 0);
INSERT INTO inventario (bodega_id, producto_id, stock_disponible, stock_reservado) VALUES (4, 15, 25, 0);

-- Los INGRESO ahora se registran como reposición directa (ya no existe
-- una tabla ORDEN_COMPRA/PROVEEDOR formal detrás del movimiento).
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (1, 1, 1, 'INGRESO', 50, DATE '2025-03-01', 'Reposicion de stock');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (2, 1, 1, 'SALIDA', 10, DATE '2025-05-20', 'Despacho pedidos iniciales');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (3, 1, 3, 'INGRESO', 20, DATE '2025-03-03', 'Reposicion de stock');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (4, 1, 3, 'SALIDA', 5, DATE '2025-05-22', 'Despacho pedidos iniciales');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (5, 2, 7, 'INGRESO', 12, DATE '2025-03-05', 'Reposicion de stock');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (6, 2, 7, 'AJUSTE', -2, DATE '2025-05-25', 'Producto danado en bodega');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (7, 4, 11, 'INGRESO', 32, DATE '2025-03-06', 'Reposicion de stock');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (8, 4, 11, 'SALIDA', 2, DATE '2025-05-28', 'Despacho pedido');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (9, 3, 14, 'INGRESO', 25, DATE '2025-03-07', 'Reposicion de stock');
INSERT INTO movimiento_inventario (movimiento_id, bodega_id, producto_id, tipo, cantidad, fecha, motivo) VALUES (10, 3, 14, 'SALIDA', 3, DATE '2025-05-30', 'Despacho pedido');

INSERT INTO cupon (cupon_id, codigo, descuento_pct, fecha_inicio, fecha_fin, usos_maximos, usos_actuales, activo) VALUES (1, 'BIENVENIDA10', 10, DATE '2025-01-01', DATE '2025-12-31', 100, 5, 'S');
INSERT INTO cupon (cupon_id, codigo, descuento_pct, fecha_inicio, fecha_fin, usos_maximos, usos_actuales, activo) VALUES (2, 'VERANO15', 15, DATE '2025-01-01', DATE '2025-03-31', 50, 50, 'N');
INSERT INTO cupon (cupon_id, codigo, descuento_pct, fecha_inicio, fecha_fin, usos_maximos, usos_actuales, activo) VALUES (3, 'FIDELIDAD5', 5, DATE '2025-01-01', DATE '2025-12-31', 200, 30, 'S');
INSERT INTO cupon (cupon_id, codigo, descuento_pct, fecha_inicio, fecha_fin, usos_maximos, usos_actuales, activo) VALUES (4, 'PRIMERACOMPRA', 20, DATE '2025-01-01', DATE '2025-12-31', 1000, 12, 'S');
INSERT INTO cupon (cupon_id, codigo, descuento_pct, fecha_inicio, fecha_fin, usos_maximos, usos_actuales, activo) VALUES (5, 'BLACKFRIDAY25', 25, DATE '2025-11-20', DATE '2025-11-30', 500, 0, 'S');

-- Pedidos y su detalle (direccion_entrega aplanada: ciudad_id_entrega + direccion_calle)
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (1, 1, 1, 1, 'Av. Libertador 123', 'depto 4B', DATE '2025-06-02', 'ENTREGADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (2, 2, 2, 2, 'Pasaje Las Rosas 20', NULL, DATE '2025-06-03', 'ENTREGADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (3, 1, 1, 1, 'Calle Los Aromos 45', 'casa esquina', DATE '2025-06-05', 'EN_PREPARACION');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (4, 3, 1, 1, 'Av. Grecia 900', NULL, DATE '2025-06-06', 'CONFIRMADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (5, 4, 3, 3, 'Calle 5 Norte 220', NULL, DATE '2025-06-07', 'ENTREGADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (6, 5, 3, 4, 'Av. Argentina 1500', 'frente a plaza', DATE '2025-06-08', 'PENDIENTE');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (7, 1, 1, 1, 'Av. Libertador 123', 'depto 4B', DATE '2025-06-10', 'ENTREGADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (8, 6, 4, 5, 'Av. Paicavi 300', NULL, DATE '2025-06-11', 'DESPACHADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (9, 2, 2, 2, 'Pasaje Las Rosas 20', NULL, DATE '2025-06-12', 'CANCELADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (10, 4, 1, 3, 'Calle 5 Norte 220', NULL, DATE '2025-06-14', 'ENTREGADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (11, 7, 1, 1, 'Av. Vitacura 4500', NULL, DATE '2025-06-15', 'CONFIRMADO');
INSERT INTO pedido (pedido_id, cliente_id, bodega_id_origen, ciudad_id_entrega, direccion_calle, direccion_referencia, fecha_pedido, estado) VALUES (12, 8, 2, 2, 'Av. Concha y Toro 88', NULL, DATE '2025-06-16', 'PENDIENTE');

INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (1, 1, 1, 189990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (1, 5, 2, 59990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (2, 6, 1, 39990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (2, 8, 2, 34990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (3, 2, 1, 149990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (3, 16, 3, 14990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (4, 3, 1, 459990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (5, 13, 1, 89990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (5, 14, 1, 179990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (6, 14, 2, 179990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (7, 1, 1, 189990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (7, 4, 1, 129990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (8, 11, 2, 69990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (8, 15, 1, 24990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (9, 7, 1, 399990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (10, 5, 1, 59990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (11, 3, 1, 459990);
INSERT INTO detalle_pedido (pedido_id, producto_id, cantidad, precio_unitario) VALUES (12, 6, 2, 39990);

-- Pagos (pedidos 6 y 12 aun PENDIENTE, sin pago; medio_pago ahora es texto directo)
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (1, 1, 'WEBPAY', 309970, 'APROBADO', DATE '2025-06-02');
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (2, 2, 'WEBPAY', 109970, 'APROBADO', DATE '2025-06-03');
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (3, 3, 'TRANSFERENCIA', 194960, 'PENDIENTE', NULL);
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (4, 4, 'WEBPAY', 459990, 'PENDIENTE', NULL);
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (5, 5, 'EFECTIVO', 269980, 'APROBADO', DATE '2025-06-07');
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (6, 7, 'WEBPAY', 319980, 'APROBADO', DATE '2025-06-10');
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (7, 8, 'TRANSFERENCIA', 164970, 'APROBADO', DATE '2025-06-11');
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (8, 9, 'WEBPAY', 399990, 'RECHAZADO', DATE '2025-06-12');
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (9, 10, 'EFECTIVO', 59990, 'APROBADO', DATE '2025-06-14');
INSERT INTO pago (pago_id, pedido_id, medio_pago, monto, estado, fecha_pago) VALUES (10, 11, 'WEBPAY', 459990, 'PENDIENTE', NULL);

INSERT INTO pedido_cupon (pedido_id, cupon_id, monto_descontado) VALUES (2, 4, 21994);
INSERT INTO pedido_cupon (pedido_id, cupon_id, monto_descontado) VALUES (5, 1, 26998);
INSERT INTO pedido_cupon (pedido_id, cupon_id, monto_descontado) VALUES (8, 3, 8249);

-- Rutas y envíos
INSERT INTO ruta (ruta_id, transportista_id, bodega_id, fecha, estado) VALUES (1, 1, 1, DATE '2025-06-02', 'FINALIZADA');
INSERT INTO ruta (ruta_id, transportista_id, bodega_id, fecha, estado) VALUES (2, 2, 2, DATE '2025-06-03', 'FINALIZADA');
INSERT INTO ruta (ruta_id, transportista_id, bodega_id, fecha, estado) VALUES (3, 4, 3, DATE '2025-06-07', 'FINALIZADA');
INSERT INTO ruta (ruta_id, transportista_id, bodega_id, fecha, estado) VALUES (4, 4, 3, DATE '2025-06-08', 'PLANIFICADA');
INSERT INTO ruta (ruta_id, transportista_id, bodega_id, fecha, estado) VALUES (5, 5, 4, DATE '2025-06-11', 'EN_CURSO');
INSERT INTO ruta (ruta_id, transportista_id, bodega_id, fecha, estado) VALUES (6, 1, 1, DATE '2025-06-10', 'FINALIZADA');
INSERT INTO ruta (ruta_id, transportista_id, bodega_id, fecha, estado) VALUES (7, 1, 1, DATE '2025-06-14', 'FINALIZADA');

INSERT INTO envio (envio_id, pedido_id, ruta_id, fecha_despacho, fecha_entrega, estado, distancia_km) VALUES (1, 1, 1, DATE '2025-06-02', DATE '2025-06-02', 'ENTREGADO', 5.2);
INSERT INTO envio (envio_id, pedido_id, ruta_id, fecha_despacho, fecha_entrega, estado, distancia_km) VALUES (2, 2, 2, DATE '2025-06-03', DATE '2025-06-03', 'ENTREGADO', 7.8);
INSERT INTO envio (envio_id, pedido_id, ruta_id, fecha_despacho, fecha_entrega, estado, distancia_km) VALUES (3, 5, 3, DATE '2025-06-07', DATE '2025-06-07', 'ENTREGADO', 12.1);
INSERT INTO envio (envio_id, pedido_id, ruta_id, fecha_despacho, fecha_entrega, estado, distancia_km) VALUES (4, 7, 6, DATE '2025-06-10', DATE '2025-06-10', 'ENTREGADO', 5.0);
INSERT INTO envio (envio_id, pedido_id, ruta_id, fecha_despacho, fecha_entrega, estado, distancia_km) VALUES (5, 8, 5, DATE '2025-06-11', NULL, 'EN_RUTA', 9.4);
INSERT INTO envio (envio_id, pedido_id, ruta_id, fecha_despacho, fecha_entrega, estado, distancia_km) VALUES (6, 10, 7, DATE '2025-06-14', DATE '2025-06-14', 'ENTREGADO', 6.3);

INSERT INTO tarifa_envio (tarifa_id, ciudad_id, peso_max_kg, costo) VALUES (1, 1, 5, 2500);
INSERT INTO tarifa_envio (tarifa_id, ciudad_id, peso_max_kg, costo) VALUES (2, 2, 5, 3000);
INSERT INTO tarifa_envio (tarifa_id, ciudad_id, peso_max_kg, costo) VALUES (3, 3, 5, 3500);
INSERT INTO tarifa_envio (tarifa_id, ciudad_id, peso_max_kg, costo) VALUES (4, 4, 5, 3200);
INSERT INTO tarifa_envio (tarifa_id, ciudad_id, peso_max_kg, costo) VALUES (5, 5, 5, 4500);

-- Postventa
INSERT INTO devolucion (devolucion_id, pedido_id, motivo, estado, fecha_solicitud) VALUES (1, 1, 'Producto llego con defecto', 'APROBADA', DATE '2025-06-05');
INSERT INTO devolucion (devolucion_id, pedido_id, motivo, estado, fecha_solicitud) VALUES (2, 2, 'Cliente se arrepintio de la compra', 'RECHAZADA', DATE '2025-06-06');
INSERT INTO devolucion (devolucion_id, pedido_id, motivo, estado, fecha_solicitud) VALUES (3, 5, 'Producto incorrecto enviado', 'SOLICITADA', DATE '2025-06-09');

INSERT INTO detalle_devolucion (devolucion_id, producto_id, cantidad, motivo_detalle) VALUES (1, 1, 1, 'Pantalla rayada');
INSERT INTO detalle_devolucion (devolucion_id, producto_id, cantidad, motivo_detalle) VALUES (1, 5, 1, 'Empaque abierto');
INSERT INTO detalle_devolucion (devolucion_id, producto_id, cantidad, motivo_detalle) VALUES (2, 6, 1, 'Ya no lo necesita');
INSERT INTO detalle_devolucion (devolucion_id, producto_id, cantidad, motivo_detalle) VALUES (3, 13, 1, 'No corresponde al pedido');

-- Puntos de fidelizacion: 1 punto por cada 10000 de compra (redondeo hacia abajo), sobre pedidos ENTREGADO
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion) VALUES (1, 1, 1, 'GANADO', 30, DATE '2025-06-02', 'Puntos por compra pedido 1');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion) VALUES (2, 2, 2, 'GANADO', 10, DATE '2025-06-03', 'Puntos por compra pedido 2');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion) VALUES (3, 4, 5, 'GANADO', 26, DATE '2025-06-07', 'Puntos por compra pedido 5');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion) VALUES (4, 1, 7, 'GANADO', 31, DATE '2025-06-10', 'Puntos por compra pedido 7');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion) VALUES (5, 4, 10, 'GANADO', 5, DATE '2025-06-14', 'Puntos por compra pedido 10');
INSERT INTO movimiento_puntos (movimiento_id, cliente_id, pedido_id, tipo, puntos, fecha, descripcion) VALUES (6, 1, NULL, 'CANJEADO', 15, DATE '2025-06-15', 'Canje por descuento');

COMMIT;

-- Nota sobre secuencias de identidad: al haberse insertado los identificadores
-- de forma explicita con columnas GENERATED BY DEFAULT AS IDENTITY, conviene
-- sincronizar el contador interno antes de insertar nuevas filas sin indicar
-- el id. Ejemplo: ALTER TABLE producto MODIFY producto_id GENERATED BY DEFAULT
-- AS IDENTITY (START WITH 17); ajustando el valor inicial al maximo utilizado
-- mas uno, en cada una de las 20 tablas que se vaya a seguir poblando.

-- Verificacion rapida de la carga (20 tablas)
SELECT 'CIUDAD' AS tabla, COUNT(*) AS filas FROM ciudad
UNION ALL SELECT 'NIVEL_FIDELIZACION', COUNT(*) FROM nivel_fidelizacion
UNION ALL SELECT 'CLIENTE', COUNT(*) FROM cliente
UNION ALL SELECT 'VENDEDOR', COUNT(*) FROM vendedor
UNION ALL SELECT 'BODEGA', COUNT(*) FROM bodega
UNION ALL SELECT 'TRANSPORTISTA', COUNT(*) FROM transportista
UNION ALL SELECT 'PRODUCTO', COUNT(*) FROM producto
UNION ALL SELECT 'INVENTARIO', COUNT(*) FROM inventario
UNION ALL SELECT 'MOVIMIENTO_INVENTARIO', COUNT(*) FROM movimiento_inventario
UNION ALL SELECT 'CUPON', COUNT(*) FROM cupon
UNION ALL SELECT 'PEDIDO', COUNT(*) FROM pedido
UNION ALL SELECT 'DETALLE_PEDIDO', COUNT(*) FROM detalle_pedido
UNION ALL SELECT 'PAGO', COUNT(*) FROM pago
UNION ALL SELECT 'PEDIDO_CUPON', COUNT(*) FROM pedido_cupon
UNION ALL SELECT 'RUTA', COUNT(*) FROM ruta
UNION ALL SELECT 'ENVIO', COUNT(*) FROM envio
UNION ALL SELECT 'TARIFA_ENVIO', COUNT(*) FROM tarifa_envio
UNION ALL SELECT 'DEVOLUCION', COUNT(*) FROM devolucion
UNION ALL SELECT 'DETALLE_DEVOLUCION', COUNT(*) FROM detalle_devolucion
UNION ALL SELECT 'MOVIMIENTO_PUNTOS', COUNT(*) FROM movimiento_puntos;
